### ISSUE TITLE
to bring p. 1.2 (Pointers) of this article in accordance with the latest EO version

### ISSUE THREAD

**Issue by Graur** [objectionary/reducing-programs-to-objects#4]
We need to make sure that all code snippets in p. 1.2 (Pointers) run successfully. And the description does not contradict the description in other articles: https://arxiv.org/pdf/2206.02585.pdf and https://arxiv.org/pdf/2111.13384.pdf

**Comment by Graur** [comment]
@MCJOHN974 please, help us here

**Comment by MCJOHN974** [comment]
@Graur I should run code snippets from reducing-programs-to-objects paper and make sure that behavior is like in this two papers, right ?

**Comment by MCJOHN974** [comment]
@Graur in what format it will be better to do that, make copy of my terminal and make some comments based on this two papers, or just say here that all is ok or open some issues will be enough ?

**Comment by Graur** [comment]
> @Graur I should run code snippets from reducing-programs-to-objects paper and make sure that behavior is like in this two papers, right ?
@MCJOHN974 You are absolutely right. This article was written based on the old EO syntax. Let's fix it!

**Comment by Graur** [comment]
> @Graur in what format it will be better to do that, make copy of my terminal and make some comments based on this two papers, or just say here that all is ok or open some issues will be enough ?

@MCJOHN974 Just a single pull request in `paper.tex` will be enough. If the paper is ok - just text here your tests, I will check them and close this issue

**Comment by Graur** [comment]
@MCJOHN974 What about the progress of this task? Do you need some help?

**Comment by MCJOHN974** [comment]
@Graur in https://github.com/objectionary/reducing-programs-to-objects/blob/5fc43b92d0b4b0add08acbb662ecf2c182f2dc8c/paper.tex#L263 pointer is used without any concrete heap. It is forbidden, right ?

**Comment by Graur** [comment]
@MCJOHN974 Yes, it is

**Comment by MCJOHN974** [comment]
Thanks, I will rewrite it with heap creation

**Comment by Graur** [comment]
@MCJOHN974 this is urgent, would be great if you put it to the highest priority

**Comment by Graur** [comment]
This is my test:
```
[] > check
  [ptr] > book
    ptr > @
    ptr.block > title
      100
      [b] (b.as-string > @)
    ptr.block > price
      8
      [b] (b.as-int > @)
  pointer. > p1
    heap 1024
    0
    108
  [p] > f
    seq > @
      book (p.add 7) > b
      b.title.write ("Object Thinking").as-bytes
      b.price
  assert-that > @
    f p1
    $.equal-to 5720251460406747220
```

**Comment by Graur** [comment]
Another one:
```
[] > check
  [x y] > foo
    x.plus y > @
  [] > f
    cage 0 > p
    seq > @
      p.write
        [x y]
          foo x y > @
      p.@ 7 42
  assert-that > @
    f
    $.equal-to 49
```
